name: Docker Build & Deploy

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract metadata (tags)
        id: meta
        run: |
          echo "SHA_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "VERSION_TAG=$VERSION" >> $GITHUB_ENV
          else
            echo "VERSION_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:${SHA_TAG} \
                       -t ${{ secrets.DOCKER_USERNAME }}/flask-app:${VERSION_TAG} \
                       . >> build.log 2>&1 | tee build.log

      - name: Upload build.log output as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Docker_build_logs
          path: build.log


      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:${SHA_TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:${VERSION_TAG}
